In [1]:
# import os # этой библиотекой переодически смотрю файлики в области видимости jupyter
import pandas as pd # для предварительного анализ
import json # первое что пришло на ум для сериализации json
from functools import reduce # еще один вариант решения который попробую, но скорее всего не самое лучшее
import sys # пригодиться для анализа

In [2]:
!python --version

Python 3.9.0

# ДЗ 1

## Предварительный анализ

In [3]:
# os.listdir()

Из личного интереса решил немного попробовать поиграться инструментом профилировки в рамках ДЗ

In [4]:
pip install memory_profiler

Requirement already satisfied: memory_profiler in c:\users\qwerty\desktop\hw\venv\lib\site-packages (0.61.0)
Requirement already satisfied: psutil in c:\users\qwerty\desktop\hw\venv\lib\site-packages (from memory_profiler) (7.2.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 20.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\users\qwerty\desktop\hw\venv\scripts\python.exe -m pip install --upgrade pip' command.

In [5]:
%load_ext memory_profiler

Предварительно изучил данные, чтобы убедиться, что словарь из правильного количества ключей.

In [6]:
df = pd.read_json('purchase_log.txt', lines=True)

In [7]:
df = df[1:] # пропускаем строку заголовка

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 1 to 99999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   99999 non-null  object
 1   category  99999 non-null  object
dtypes: object(2)
memory usage: 1.5+ MB

In [9]:
df.head()

      user_id         category
1  1840e0b9d4         Продукты
2  4e4f90fcfb      Электроника
3  afea8d72fc      Электроника
4  373a6055fe  Бытовая техника
5  9b2ab046f3      Электроника

In [10]:
len(df['user_id'].unique()) # необходимо для валидации результата

99517

Так как задача по сути сведения к хэш таблице неких логов, то число - 99517 потребуется для сравнения результатов.

In [11]:
len(df['category'].unique()) # факультативная статистика, личный интерес

7

In [12]:
# еще одна факультативная статистика, личный интерес

In [13]:
category_df = df.groupby('category')['user_id'].count().reset_index().sort_values(by='user_id', ascending=False)
category_df

                 category  user_id
5             Электроника    33466
0         Бытовая техника    23670
2                Продукты    14010
1                   Досуг    11783
3  Строительство и ремонт     9009
4     Товары для животных     7028
6           не определена     1033

In [14]:
category_df['category'].unique()

array(['Электроника', 'Бытовая техника', 'Продукты', 'Досуг',
       'Строительство и ремонт', 'Товары для животных', 'не определена'],
      dtype=object)

Так как количество строк 99999 и количество пользователй 99517, то имеет смысл сделать агрегат по user_id и посмотреть, какие категории повторяются

In [15]:
data_agg = df.groupby('user_id')['category'].agg(','.join)

In [16]:
data_agg = df.groupby('user_id')['category'].agg(
    categories=', '.join,
    count='count',
)

In [17]:
df_gte2 = (data_agg[data_agg['count'] >= 2]).reset_index()
df_gte2

        user_id                               categories  count
0    0061aaf3f9                    Продукты, Электроника      2
1    02a3642b58      Электроника, Строительство и ремонт      2
2    02ce3f6ba4                   Досуг, Бытовая техника      2
3    02fd760e37  Бытовая техника, Строительство и ремонт      2
4    03787309eb      Строительство и ремонт, Электроника      2
..          ...                                      ...    ...
476  fd3c2d449c  Бытовая техника, Строительство и ремонт      2
477  fe94c62069             Электроника, Бытовая техника      2
478  ffb4426f85                       Досуг, Электроника      2
479  ffb83955b3                    Электроника, Продукты      2
480  ffd34380bc             Электроника, Бытовая техника      2

[481 rows x 3 columns]

In [18]:
data_agg['count'].sum() # никаких аномалий при группировке нет, ничего не дропнулось, все данные на месте

np.int64(99999)

В случае хэш такблиц(словарь), пользователи имеющие более одной категории будут перетирать значения по мере выполнения цикла.
ДЗ звучит так буд-то это и подразумевалос.
Дополнительно приложу еще свой вариант решения.

## Решение

In [19]:
def parse_log1():
    purchase_dict = {}
    with open('purchase_log.txt',  mode='r',  encoding='utf-8',) as f:
        f.readline()
        for l in f:
            data = json.loads(l)
            purchase_dict[data['user_id']] = data['category']
    return purchase_dict

In [20]:
def parse_log2():
    purchase_dict = {}
    with open('purchase_log.txt',  mode='r',  encoding='utf-8',) as f:
        f.readline()
        purchase_dict = dict(
            map(
                lambda d: (d['user_id'], d['category']),
                map(json.loads, f)
               )
        )
    return purchase_dict

In [21]:
def parse_log3():
    purchase_dict = {}
    with open('purchase_log.txt',  mode='r',  encoding='utf-8',) as f:
        f.readline()
        data = f.read().splitlines()
        # пилим строку. Должно работать быстрее, но когнитивно тяжелее воспринимать
        purchase_dict = {
                str.partition(str.partition(l, '"user_id": "')[2], '"')[0]:
                str.partition(str.partition(l, '"category": "')[2], '"')[0]
                for l in data
        }
    return purchase_dict

In [22]:
def parse_log4():
    purchase_dict = {}
    with open('purchase_log.txt',  mode='r',  encoding='utf-8',) as f:
        f.readline()  
        return reduce(
            lambda acc, d: acc.update({d['user_id']: d['category']}) or acc,
            map(json.loads, f),
            {}, 
        )

##  Профилирование (личное любопытство)

In [23]:
%memit pass # общее потребление Python

peak memory: 159.85 MiB, increment: 0.06 MiB

In [24]:
%timeit -n 2 -r 5 parse_log1()

148 ms ± 1.76 ms per loop (mean ± std. dev. of 5 runs, 2 loops each)

In [25]:
%memit -r 10 parse_log1()

peak memory: 163.07 MiB, increment: 2.53 MiB

In [26]:
%timeit -n 2 -r 5 parse_log2()

163 ms ± 8.29 ms per loop (mean ± std. dev. of 5 runs, 2 loops each)

In [27]:
%memit -r 10 parse_log2()

peak memory: 163.09 MiB, increment: 2.52 MiB

In [28]:
%timeit -n 2 -r 5 parse_log3()

74.3 ms ± 1.2 ms per loop (mean ± std. dev. of 5 runs, 2 loops each)

In [29]:
%memit -r 10 parse_log3()

peak memory: 177.18 MiB, increment: 15.14 MiB

In [30]:
%timeit -n 2 -r 5 parse_log4()

155 ms ± 3.5 ms per loop (mean ± std. dev. of 5 runs, 2 loops each)

In [31]:
%memit -r 10 parse_log4()

peak memory: 164.60 MiB, increment: 2.54 MiB

## Анализ результатов

In [32]:
p1 = parse_log1()
p2 = parse_log2()
p3 = parse_log3()
p4 = parse_log4()

In [33]:
p1 == p2 == p3 == p4

True

In [34]:
len(p1.keys())

99517

результат сопоставим с количеством пользователей из user_id

 - parse_log1 - лучший по когнитивной нагрузке
 - parse_log3 - самый быстрый, но вероятно легко сломается при дополнении структуры json, новыми параметрами. Особенно если делитель строки будет попадать шаблоном в них
 - parse_log2 и parse_log4 - в данном случае бестолковые способы, так как тяжелее воспринимать, дебажить, дополнять.

## Вывод результатов(для фиксации выполнения)

In [35]:
p1

{'1840e0b9d4': 'Продукты',
 '4e4f90fcfb': 'Электроника',
 'afea8d72fc': 'Электроника',
 '373a6055fe': 'Бытовая техника',
 '9b2ab046f3': 'Электроника',
 '9f39d307c3': 'Электроника',
 '44edeffc91': 'Продукты',
 '704474fa2d': 'Продукты',
 '1de31be403': 'Бытовая техника',
 'b71f36a5e4': 'Продукты',
 '79843a685a': 'Продукты',
 'ff68cee0d6': 'Бытовая техника',
 'e8447c40e2': 'Досуг',
 '98d290be27': 'Электроника',
 'fa0079a5a8': 'Досуг',
 '22d2f03a17': 'Досуг',
 '3f8e1ccd3f': 'Электроника',
 '81a9988b83': 'Электроника',
 '65f44a2eb7': 'Досуг',
 '5f8fbb0149': 'Бытовая техника',
 '3ecff691fd': 'Электроника',
 'dd0e912251': 'Электроника',
 '9250593d55': 'Электроника',
 '37c4e090e4': 'Электроника',
 '22fa3ea76f': 'Электроника',
 '73b876b237': 'Электроника',
 'f983a69d67': 'Товары для животных',
 '4ea17212f8': 'Продукты',
 'c6de96a5e2': 'Товары для животных',
 'd8e3bcee53': 'Продукты',
 '680aa815f9': 'Продукты',
 '4a92a68cf9': 'Электроника',
 '905e60cb52': 'Бытовая техника',
 '393bcfb298': 'Продукты',
 '06d450cc57': 'Электроника',
 'b60ce22f17': 'Электроника',
 '6f159c4c2e': 'Товары для животных',
 '564202f6bd': 'Электроника',
 '1908683775': 'Электроника',
 '8fd957a463': 'Продукты',
 '72e0a3f1d0': 'Бытовая техника',
 '7f5f56e517': 'Досуг',
 'bc1a0a7e26': 'Досуг',
 '17639fe89d': 'Досуг',
 '74c9201f84': 'Электроника',
 'bc4ebda0df': 'Досуг',
 'fe4615dd15': 'Досуг',
 'd2c560746d': 'Бытовая техника',
 'f0a93d52d2': 'Электроника',
 'fe52ded300': 'Электроника',
 'dbe70d84e4': 'Строительство и ремонт',
 'f660dbcc3f': 'Электроника',
 'f93283c9ee': 'Бытовая техника',
 '66bea9bf58': 'Бытовая техника',
 '111c52d9bc': 'Продукты',
 '16dc76e94d': 'Электроника',
 '87f37b380c': 'Продукты',
 '830421d975': 'Продукты',
 '7d6c62f0a2': 'Бытовая техника',
 '77465a0b61': 'Бытовая техника',
 'ee9eb52181': 'Товары для животных',
 '871c1fa9ae': 'Продукты',
 '03b91dba06': 'Электроника',
 '6cb42b2632': 'Бытовая техника',
 '9ab8f3bbb8': 'Бытовая техника',
 '63df9ee9d3': 'Электроника',
 '2ffd6c724d': 'Продукты',
 'af24cffd03': 'Электроника',
 '421149bb9a': 'Строительство и ремонт',
 '24300c6d1c': 'Электроника',
 '9ca11a651f': 'Электроника',
 'b7e640032f': 'Электроника',
 '3691ad282b': 'Электроника',
 '00ea2f7484': 'Электроника',
 '6f198ac1c9': 'Бытовая техника',
 '0d479d4259': 'Электроника',
 'b461051101': 'Досуг',
 'd39a1d56c3': 'Бытовая техника',
 '316ab03143': 'Товары для животных',
 '78ed39a415': 'Электроника',
 '19d1e4e036': 'Товары для животных',
 '9e765c6822': 'Продукты',
 'ddd50eaa45': 'Электроника',
 'c21b82499e': 'Электроника',
 'da79d9ff30': 'Товары для животных',
 'eded5c6792': 'Досуг',
 'e3654c7f1a': 'Досуг',
 'd20bf10c78': 'Бытовая техника',
 '12de58d8e6': 'Продукты',
 'de85ea0eb6': 'Электроника',
 'dfe6f4ebb4': 'Бытовая техника',
 '9d25ac3886': 'Досуг',
 'd47dd8b814': 'Электроника',
 'c5e1bf636a': 'Электроника',
 'a86e69db63': 'Продукты',
 '91802f78b2': 'Электроника',
 '152ea9bb42': 'Бытовая техника',
 '06569907e6': 'Бытовая техника',
 '9f5bf9b73f': 'Строительство и ремонт',
 'ec11793734': 'Продукты',
 '0cf6ee6c84': 'Бытовая техника',
 'f9a3ef9ac2': 'Продукты',
 '716a1b4e10': 'Продукты',
 '426fa041ad': 'Электроника',
 'c0cd6e93e6': 'Электроника',
 '85ff218333': 'Строительство и ремонт',
 'f537f6c8ea': 'Бытовая техника',
 '749e8694c5': 'Товары для животных',
 '29586e4061': 'Продукты',
 'e9eaffa80a': 'Бытовая техника',
 'da237781d5': 'Продукты',
 'b7195283e1': 'Товары для животных',
 '62f37b821c': 'Досуг',
 '69ae0afab1': 'Продукты',
 '7fa3bf64b4': 'Досуг',
 '4e603d8878': 'Строительство и ремонт',
 '6812661e1c': 'Электроника',
 '6aff7a1677': 'Бытовая техника',
 '88afad2ad9': 'Продукты',
 '0fa7c5b19c': 'Товары для животных',
 'bed9ab14bd': 'Товары для животных',
 '397005e41e': 'Бытовая техника',
 '80023b95ac': 'Электроника',
 '9fb91262f8': 'Бытовая техника',
 'f34a165ad2': 'Электроника',
 '5b7c1e9769': 'Бытовая техника',
 '5655da0e0b': 'Электроника',
 'ef33021c36': 'не определена',
 'b15321ea7c': 'Продукты',
 '0d4f4664e0': 'Продукты',
 'a2468d6c33': 'Электроника',
 'a8660dcfae': 'Бытовая техника',
 'a7bfa5d0cc': 'Досуг',
 '6e6293a54b': 'Досуг',
 '48b9ea8b65': 'Электроника',
 'fb9acee964': 'Бытовая техника',
 '69775511be': 'Досуг',
 '95bf67fda9': 'Продукты',
 'ca899d23dd': 'Бытовая техника',
 '2de051e056': 'Электроника',
 '0da9ca70fe': 'Продукты',
 'fcc5bebc42': 'Бытовая техника',
 '51f6ce88cc': 'Бытовая техника',
 '74a55eee1d': 'Электроника',
 '69475b45df': 'Бытовая техника',
 '816800e62f': 'Бытовая техника',
 '28ce699720': 'Бытовая техника',
 'f0d57ef042': 'Электроника',
 'c577b4b31e': 'Продукты',
 '4038202869': 'Электроника',
 '1405e18ffb': 'Досуг',
 'c0cc01a6a4': 'Электроника',
 '4cd8bde9ac': 'Продукты',
 '8c5eeb346a': 'Бытовая техника',
 '853f7ea287': 'Продукты',
 '3b1fb2ad3f': 'Электроника',
 '8c45fdbf5a': 'Электроника',
 'a6a4ff39f8': 'Бытовая техника',
 '55effa36e0': 'Продукты',
 '51d4f4b9d5': 'Бытовая техника',
 '33a4dbd193': 'Электроника',
 'bc2b6ade51': 'Электроника',
 'e371c40a07': 'Электроника',
 '74d3a4830b': 'Продукты',
 'fceaddb1f5': 'Электроника',
 '63f9ec63df': 'Бытовая техника',
 'a7091d1405': 'Бытовая техника',
 'c74d0b4602': 'Электроника',
 'a8c4da0681': 'Электроника',
 '47ec449fbe': 'Строительство и ремонт',
 '9b63ed579f': 'Строительство и ремонт',
 '508e26d325': 'Электроника',
 '9cdc26ff6c': 'Электроника',
 'be8c8f1a63': 'Продукты',
 'bc40fc5c3b': 'Продукты',
 '5bc256883c': 'Электроника',
 '800ad1974f': 'Электроника',
 '36b0b3a179': 'Бытовая техника',
 'fbcb38042a': 'Бытовая техника',
 'b3fe11defe': 'Продукты',
 '1909ff3b18': 'Продукты',
 'cc85b81371': 'Продукты',
 '36d248e31c': 'Продукты',
 '84b1b23768': 'Досуг',
 '44174c696c': 'Продукты',
 '2e8723f652': 'Продукты',
 '2ffcf27605': 'Бытовая техника',
 '94e132ac2a': 'Досуг',
 '24c047fa51': 'Электроника',
 '30fa49eb81': 'Бытовая техника',
 'd9a640bee2': 'Электроника',
 '8684af0a5d': 'Досуг',
 'bbec49524b': 'Электроника',
 'e95d728116': 'Продукты',
 '5392a9dd06': 'Строительство и ремонт',
 '8c9c7efbdb': 'Бытовая техника',
 '8e7cb8744a': 'Продукты',
 'a41b59347a': 'не определена',
 'c1a0da9976': 'Электроника',
 '9e7126c1f7': 'Строительство и ремонт',
 '49e9a83a56': 'Электроника',
 'b3391af5f3': 'Бытовая техника',
 '9c4d9e37b8': 'Электроника',
 '1eee1b1995': 'Электроника',
 'd61df629df': 'Продукты',
 'f67f61db9e': 'Электроника',
 '73d9a7f6d5': 'Продукты',
 '5ebea046cd': 'Электроника',
 'eb7ff574cc': 'Электроника',
 'ccfa85981e': 'Бытовая техника',
 '3def3c47e0': 'Электроника',
 '56183e3be7': 'Продукты',
 '5a8c6a6214': 'Досуг',
 'f99c733c58': 'Электроника',
 '301db812db': 'Электроника',
 '27be75d1bf': 'Электроника',
 'ba38172577': 'Досуг',
 'f0706bb95e': 'Продукты',
 'ac317ed5da': 'Электроника',
 'd2e5eece34': 'Бытовая техника',
 '5e5398d531': 'Электроника',
 '8b2f2ce9f1': 'Электроника',
 '81ebf6e699': 'Электроника',
 '2ffc0ac898': 'Продукты',
 '3953e7d027': 'Электроника',
 'abbaaeeec6': 'Товары для животных',
 'b3347f9015': 'Электроника',
 '5f4ccaec06': 'Электроника',
 '61f09c8e23': 'Электроника',
 'd4004b3288': 'Досуг',
 'ccdb17354a': 'Продукты',
 '1165b9e353': 'Досуг',
 '0a22ae5507': 'Электроника',
 'e43e102688': 'Досуг',
 '7e33fda510': 'Электроника',
 '2da9fe5598': 'Электроника',
 'bdec18f74e': 'Продукты',
 '41a4f49b7f': 'Электроника',
 '9df56d0753': 'Продукты',
 'c86f800915': 'Бытовая техника',
 '422ac66d5a': 'Электроника',
 '7ff7a48697': 'Электроника',
 'd8557c45f3': 'Продукты',
 '04405bf835': 'Продукты',
 '987dc6321c': 'Электроника',
 '48a32ff3cc': 'Электроника',
 'deba35d5a8': 'Бытовая техника',
 '42ec6aa3cb': 'Продукты',
 '3f93050f90': 'Досуг',
 '8a0c7e0dfc': 'Товары для животных',
 '73aa62d288': 'Электроника',
 '3e75e9c62e': 'Электроника',
 'c9ca4f00dd': 'Продукты',
 '72d11d2013': 'Бытовая техника',
 '991072196d': 'Бытовая техника',
 '092337723c': 'Электроника',
 '642295148f': 'Электроника',
 'e8dcb49bc2': 'Досуг',
 'f127ee3e08': 'Бытовая техника',
 '78c61cf048': 'Электроника',
 '28ed9a2680': 'Товары для животных',
 '547434b3fc': 'Строительство и ремонт',
 'ec0d778ca8': 'Электроника',
 '8c6a576009': 'Бытовая техника',
 '26daa6bcff': 'Товары для животных',
 '63eea77eac': 'Досуг',
 'a771274455': 'Строительство и ремонт',
 'c92680024a': 'Досуг',
 '0f359c5def': 'Электроника',
 '81b86551e0': 'Товары для животных',
 'b694d9fb7e': 'не определена',
 '2feeed4e90': 'Электроника',
 'e50f766aee': 'Электроника',
 '773030b2e2': 'Бытовая техника',
 'a760d2ebe8': 'Электроника',
 'b45d0d2b02': 'Электроника',
 'da177dee2e': 'Досуг',
 'e2389b2f7d': 'Электроника',
 '9443ea597f': 'Строительство и ремонт',
 'c9d93ee37c': 'Электроника',
 '122eafaf38': 'Продукты',
 '9b2ff5eba6': 'Бытовая техника',
 '282ee749cd': 'Продукты',
 '4b1bc949e6': 'Продукты',
 'a5669f7711': 'Товары для животных',
 'ca20e247ce': 'Продукты',
 'f88b4269c5': 'Товары для животных',
 '8afd34ea5d': 'Электроника',
 '0b964583be': 'Продукты',
 '2419ce61b8': 'Досуг',
 '4dd2890bda': 'Электроника',
 '2e74cb6a8a': 'Электроника',
 'db51313879': 'Продукты',
 'c31aa4037a': 'не определена',
 'ffde2d54b0': 'Электроника',
 '23b5af6334': 'не определена',
 'ba076e04d6': 'Электроника',
 '1a9515473a': 'Товары для животных',
 '2571da9158': 'Строительство и ремонт',
 'a546b7ee7c': 'Досуг',
 'a677351888': 'Электроника',
 '64bcd9b25a': 'Строительство и ремонт',
 '0a96362e4d': 'Бытовая техника',
 '854a5623f0': 'Продукты',
 'da4df206c2': 'Строительство и ремонт',
 'f744545cc3': 'Бытовая техника',
 '7af958b044': 'Товары для животных',
 '3ea58635a3': 'Электроника',
 '3258e62b94': 'Электроника',
 '262f3fc8b5': 'Электроника',
 '18e33e0244': 'Электроника',
 '5f58fedc8c': 'Строительство и ремонт',
 '1c29031015': 'Бытовая техника',
 'eb986e44ed': 'Электроника',
 '5f8e41e9fe': 'Бытовая техника',
 '932ddf4781': 'Досуг',
 '7675997d49': 'Досуг',
 '5987dcf8a4': 'Бытовая техника',
 '89df00704c': 'Строительство и ремонт',
 'c2d2d8ac77': 'Бытовая техника',
 'c9c47cbb3e': 'Досуг',
 'dc5e2c99dd': 'Электроника',
 'f5ec9a5cd3': 'Досуг',
 'e6d9f9266d': 'Продукты',
 '9cefeea76d': 'Бытовая техника',
 '2462308ce7': 'Продукты',
 'e65eedc757': 'Электроника',
 '52b1d2a63f': 'Продукты',
 '76802021e9': 'Электроника',
 'a7e81df232': 'Досуг',
 '1aa5be530e': 'Продукты',
 '28f52a3a57': 'Электроника',
 '05cbde31c9': 'Бытовая техника',
 '63999d7c25': 'Электроника',
 '367da43c26': 'Электроника',
 '95161a6ab0': 'Электроника',
 '706501f197': 'Бытовая техника',
 '151f96dc65': 'Строительство и ремонт',
 '65b8c9a2a4': 'Строительство и ремонт',
 'ce57bf3770': 'Бытовая техника',
 '69d7a3a6b7': 'Электроника',
 '64d25949ee': 'Электроника',
 '8e8f91533b': 'Продукты',
 '301f91129f': 'Бытовая техника',
 '8a4fbf45b2': 'Товары для животных',
 'bfd49a9403': 'Продукты',
 '4f7a7b927c': 'Электроника',
 'a684d11d7f': 'Продукты',
 '6fb5f6efb3': 'Продукты',
 '9a1538d1d4': 'Бытовая техника',
 '5331a15167': 'Продукты',
 '597f7b8898': 'Продукты',
 'e0205c7f6f': 'Продукты',
 'fc4b00bcd2': 'Досуг',
 'c3e109ab54': 'Продукты',
 '93564b2f07': 'Электроника',
 'a9fd3b61ee': 'Бытовая техника',
 '3f17e0ae70': 'Электроника',
 '5574f1d3f7': 'Электроника',
 '6c1e59bd4c': 'Бытовая техника',
 'ed11062209': 'Досуг',
 'd829f42876': 'Досуг',
 'd2c684f09e': 'Электроника',
 '4a96c9c66a': 'Электроника',
 '190a767c80': 'Электроника',
 '1a95786640': 'Продукты',
 'd1d24d5736': 'Строительство и ремонт',
 'a10da0093b': 'Продукты',
 '562ec95cde': 'Досуг',
 'b5e2f0a283': 'Продукты',
 '30aa6019ee': 'Строительство и ремонт',
 '06c037d78b': 'Электроника',
 '3880135278': 'Электроника',
 'f76845f07c': 'Электроника',
 'a3c460b857': 'Продукты',
 'a9e50fec42': 'Электроника',
 'df5cf7f69a': 'Бытовая техника',
 'dd3f58cee5': 'Досуг',
 '9ecb0bed11': 'Электроника',
 '03da4195d5': 'Электроника',
 'b1c4466083': 'Продукты',
 '415f8fd5c6': 'Товары для животных',
 'de56717d46': 'Электроника',
 '5227f15c20': 'Электроника',
 '771c115971': 'Строительство и ремонт',
 'cf893f680f': 'Электроника',
 '47f4301c42': 'Строительство и ремонт',
 'e95d23f9ae': 'Строительство и ремонт',
 'd1d6f9b416': 'Электроника',
 '2fe04b4c3a': 'Продукты',
 '6cd9581955': 'Электроника',
 '73521732bf': 'Продукты',
 'c80ea6d678': 'Строительство и ремонт',
 '68d3f7a732': 'Бытовая техника',
 'a60013a070': 'Бытовая техника',
 '354d5aefc8': 'Продукты',
 'ae939da2e6': 'Продукты',
 'efc11b447d': 'Продукты',
 'f91ea585fa': 'Продукты',
 '654fd1a3d4': 'Бытовая техника',
 '2be1d9f2dd': 'Электроника',
 'eed9621d35': 'Электроника',
 '5da0bbd1a2': 'Продукты',
 'b49e94e319': 'Бытовая техника',
 'c1e9992871': 'Бытовая техника',
 'cdb8ff1123': 'Строительство и ремонт',
 '540494af82': 'Электроника',
 '84a6137053': 'не определена',
 '616be967a6': 'Товары для животных',
 '74d4880314': 'Досуг',
 '4cac4d415e': 'Строительство и ремонт',
 '38c3ba4023': 'Электроника',
 '4b58237c1c': 'Электроника',
 '64f7b50d91': 'Продукты',
 '40a0c7e9fd': 'Бытовая техника',
 '62f6430779': 'Продукты',
 '28e6a3401e': 'Бытовая техника',
 '97e4995f30': 'Строительство и ремонт',
 'c7a0815ba6': 'Бытовая техника',
 '3a120dff00': 'Продукты',
 '2d3c9b5eaf': 'Товары для животных',
 'dec8283dc2': 'Электроника',
 'b693664c57': 'Продукты',
 'f7075c9aa0': 'Досуг',
 '62b23ee4ec': 'Электроника',
 'b401bb84c5': 'Электроника',
 '6e474050be': 'Бытовая техника',
 'e13c44fa95': 'Продукты',
 '7e647f1627': 'Досуг',
 'ba15a9c30d': 'Досуг',
 '5f7338c6d2': 'Электроника',
 'b8ec83addc': 'Электроника',
 '2b3d1447aa': 'Строительство и ремонт',
 '90055fc6ca': 'Электроника',
 '8699d6bfa4': 'Досуг',
 '15626f0e4b': 'Электроника',
 '5b7a18599d': 'Продукты',
 '73c4b254fd': 'Строительство и ремонт',
 '27c802ea37': 'Электроника',
 'b2472945fb': 'Электроника',
 'a8d0360a31': 'Бытовая техника',
 '4a6d6258da': 'Электроника',
 '2942d52d8f': 'Продукты',
 '77f350285d': 'Электроника',
 'f848112c51': 'Строительство и ремонт',
 'b323f423ad': 'Бытовая техника',
 '54d4e81534': 'Электроника',
 '045b8e93fb': 'Товары для животных',
 '8acfca3a2c': 'Строительство и ремонт',
 'b41d5a7e8b': 'Продукты',
 'bccd9951e1': 'Продукты',
 'adf6dc7f13': 'Продукты',
 '9d619cb825': 'Товары для животных',
 '1f75239f09': 'Электроника',
 '6c13c61421': 'Бытовая техника',
 'c85703bb83': 'Электроника',
 '96ea47dccc': 'Продукты',
 'bb6bc25682': 'Бытовая техника',
 '31f083b890': 'Электроника',
 '96f1cdc32a': 'Электроника',
 'a6064a81b0': 'Бытовая техника',
 '69368a4512': 'Досуг',
 'a39eeffc02': 'Электроника',
 '9e431b36b4': 'Строительство и ремонт',
 '1af6b519ef': 'Бытовая техника',
 '73e1fe10eb': 'Электроника',
 '463ba5e7a4': 'Бытовая техника',
 '12a4a922a1': 'Продукты',
 'c3507551c1': 'Бытовая техника',
 'ff0f3a4f31': 'Бытовая техника',
 'a14266b0c8': 'Электроника',
 'ed9a053f22': 'Строительство и ремонт',
 '7c410bc984': 'Продукты',
 '43d3eef688': 'Продукты',
 '2863b7f7a8': 'Электроника',
 'c6cf274c7c': 'Бытовая техника',
 '032bed90db': 'Продукты',
 'bd5d165524': 'Электроника',
 '087deeada3': 'Электроника',
 'be4e078bfe': 'Бытовая техника',
 'e9c183b31b': 'Электроника',
 'd623033e42': 'Электроника',
 'b2eae573f9': 'Электроника',
 '0f70a51e4f': 'Электроника',
 'cab50d2e67': 'не определена',
 'cce8f9f201': 'Досуг',
 '4ec1430612': 'Бытовая техника',
 'ddeffbfe0d': 'Продукты',
 'fe8d2e419e': 'Электроника',
 '22559638aa': 'Продукты',
 '5c8b3f960b': 'Строительство и ремонт',
 'ab3b5c58c4': 'Досуг',
 '2ba40c1c01': 'Строительство и ремонт',
 '4823c187c8': 'Электроника',
 '41f6d99050': 'Строительство и ремонт',
 'c60a01a400': 'Бытовая техника',
 '4068465b5c': 'Электроника',
 '644c0e1db3': 'Бытовая техника',
 '9b8a4ed047': 'Продукты',
 '2f7aabdc85': 'Продукты',
 '804500fb95': 'Бытовая техника',
 '12999dcd9a': 'Товары для животных',
 'c07439237e': 'Электроника',
 '3e591c3ffc': 'Бытовая техника',
 '7ffdf9d121': 'Товары для животных',
 'bae8553cf5': 'Электроника',
 'c612258cb7': 'Строительство и ремонт',
 '4dfa3cdd1c': 'Бытовая техника',
 '92c228eb3e': 'Бытовая техника',
 '6c0e66a66f': 'Бытовая техника',
 '49d3c0fa39': 'Товары для животных',
 '0bb0401efe': 'Электроника',
 'f5d17124c3': 'Досуг',
 '2face57c42': 'Досуг',
 '02d90d34aa': 'Продукты',
 '75f5d0d207': 'Досуг',
 'e992cb1fc7': 'Электроника',
 '20de5fe407': 'Электроника',
 '019d3a0a03': 'Бытовая техника',
 'b23d63fafa': 'Электроника',
 'b38932bf38': 'Досуг',
 '1035729344': 'Досуг',
 '231bac1fca': 'Электроника',
 '61fc9f74de': 'Электроника',
 'c438a203ed': 'Продукты',
 'e1738778ac': 'Электроника',
 '901b681a19': 'Досуг',
 '70a3a8f1c0': 'Бытовая техника',
 '2518ee608a': 'Досуг',
 'b602da8f4f': 'Бытовая техника',
 'd01030d1b8': 'Продукты',
 '1460f00675': 'Бытовая техника',
 '02e9d12fa3': 'Продукты',
 '1f6a93cfd0': 'Товары для животных',
 '779cec4e6f': 'Строительство и ремонт',
 '5c02b413ca': 'Электроника',
 'bd0bfb6081': 'Досуг',
 '7cae20cdba': 'не определена',
 'ce09a96893': 'Электроника',
 '824d7dc1da': 'Электроника',
 '7acbdd5863': 'Электроника',
 '14375d7acf': 'Досуг',
 '183f8294db': 'Электроника',
 '735284e60a': 'Бытовая техника',
 'ebbf18454c': 'Продукты',
 'f0786e4328': 'Продукты',
 '98d1b06887': 'Бытовая техника',
 '33998afd1c': 'Бытовая техника',
 'ffba436cd9': 'Продукты',
 'ea0d8049e3': 'Бытовая техника',
 '73cbbc4961': 'Электроника',
 'd3ff27f68f': 'Электроника',
 '08b19ca06d': 'Строительство и ремонт',
 '176742fa25': 'Досуг',
 'a4efe5d448': 'Товары для животных',
 '4d3c6aadf5': 'Товары для животных',
 'dfa1420acf': 'Бытовая техника',
 '4454d85843': 'Продукты',
 '9112bccd2d': 'Бытовая техника',
 'de83486cc6': 'Продукты',
 '51b17d710d': 'Электроника',
 '74b631217b': 'Продукты',
 '2081cf7480': 'Бытовая техника',
 'fc8192c9c8': 'Электроника',
 '14c31e0c1e': 'Досуг',
 '449505c9d8': 'Электроника',
 '94476a8369': 'Продукты',
 'a43dd86c56': 'Бытовая техника',
 '1e2c265bc4': 'Электроника',
 'dba645a04f': 'Бытовая техника',
 '4f2bd5f70d': 'Бытовая техника',
 '48569e217e': 'Бытовая техника',
 '5b1e50821f': 'Бытовая техника',
 '5abab820de': 'Бытовая техника',
 '77f36555ba': 'Товары для животных',
 '283f97cfcd': 'Электроника',
 'e2e42f795f': 'Бытовая техника',
 'cff62d9d8e': 'Продукты',
 '5a6a6d309d': 'Электроника',
 'ae475d4bb1': 'Электроника',
 '499a53c9a8': 'Бытовая техника',
 'e9fb6de839': 'Бытовая техника',
 'f6f7df5f4d': 'Электроника',
 'e415de2b18': 'Бытовая техника',
 'ab426cced0': 'Строительство и ремонт',
 'e64b03a160': 'Электроника',
 '1759a9325d': 'Бытовая техника',
 '845b7880ee': 'Электроника',
 'c4054ed775': 'Электроника',
 '2b1728c429': 'Досуг',
 'e791d1a212': 'Продукты',
 'bfe28de286': 'Бытовая техника',
 '7da375021d': 'Электроника',
 'c4edc286b8': 'Досуг',
 '60eb5f8170': 'Досуг',
 '79440400e3': 'Электроника',
 'e6ee1d8d89': 'Строительство и ремонт',
 '243d7e0a95': 'Бытовая техника',
 'bd460f3405': 'Электроника',
 '109fbe07f7': 'Строительство и ремонт',
 '3bd3d1c5e8': 'Электроника',
 '4297890da8': 'Досуг',
 '10738c47a7': 'Бытовая техника',
 '3baee3d19a': 'Электроника',
 '537009ef49': 'не определена',
 'b667cd3778': 'Досуг',
 '7189a26266': 'Электроника',
 '66c75a1c8a': 'Бытовая техника',
 '3efb665357': 'Бытовая техника',
 'a7df231fed': 'Электроника',
 'eb17b6b1b7': 'Досуг',
 'd7690ca4c0': 'Электроника',
 'da7e65a871': 'Бытовая техника',
 'ded9654377': 'Продукты',
 '0e0e510d59': 'Электроника',
 '382d1a5a62': 'Досуг',
 'b479a779b7': 'Электроника',
 '8bb76cf91e': 'Бытовая техника',
 '032f356576': 'Продукты',
 '7bede4fcf2': 'Бытовая техника',
 '588e139e53': 'Бытовая техника',
 '478fa069a6': 'Бытовая техника',
 'e759ec098f': 'Электроника',
 'cf42cc3472': 'Бытовая техника',
 '3a0c09c22c': 'Бытовая техника',
 '455f76a9f1': 'Бытовая техника',
 '97e1482d3e': 'Бытовая техника',
 '52730c206f': 'Бытовая техника',
 '876653621b': 'Электроника',
 '59c0e968a7': 'Товары для животных',
 '8cd25fc2bb': 'Бытовая техника',
 '6dec44a650': 'Бытовая техника',
 '5c84a195c6': 'Досуг',
 '761be8357b': 'Электроника',
 '276ebc89f2': 'Строительство и ремонт',
 'e69eb9b5d9': 'Электроника',
 '3f82695909': 'Досуг',
 '13d6468f64': 'Электроника',
 'b854e3b51d': 'Электроника',
 'd844dbef73': 'Продукты',
 '4c56fa14c1': 'Бытовая техника',
 '6b5f868b94': 'Электроника',
 '557af23bea': 'Бытовая техника',
 '30935f492b': 'Электроника',
 'c2e5400687': 'Продукты',
 'c8bc5285c1': 'Бытовая техника',
 '5fd0c516ee': 'Электроника',
 'b73deb623a': 'Электроника',
 '624b96fe4f': 'Досуг',

In [36]:
for i, (user_id, category) in enumerate(p1.items()):
    if i >= 2:
        break
    print(f'{user_id} ‘{category}‘')

1840e0b9d4 ‘Продукты‘
4e4f90fcfb ‘Электроника‘

## Дополнительный разбор в случае дублей пользователей

В блоке анализа мной найдены дубликаты идентификаторов пользователей. 
Для логов вполне ожидаемо иметь дубли, и скорее всего имеет смысл обработать их иначе. 
Ниже представлен контрольный пользователь `0061aaf3f9`, который имеет категории: Продукты, Электроника.
Но в связи с особенностями слоаварей, перезатирается. В условии задачи ничего не сказано по этому поводую

In [37]:
df_gte2.iloc[0:] # категории на самом деле

        user_id                               categories  count
0    0061aaf3f9                    Продукты, Электроника      2
1    02a3642b58      Электроника, Строительство и ремонт      2
2    02ce3f6ba4                   Досуг, Бытовая техника      2
3    02fd760e37  Бытовая техника, Строительство и ремонт      2
4    03787309eb      Строительство и ремонт, Электроника      2
..          ...                                      ...    ...
476  fd3c2d449c  Бытовая техника, Строительство и ремонт      2
477  fe94c62069             Электроника, Бытовая техника      2
478  ffb4426f85                       Досуг, Электроника      2
479  ffb83955b3                    Электроника, Продукты      2
480  ffd34380bc             Электроника, Бытовая техника      2

[481 rows x 3 columns]

In [38]:
p1['0061aaf3f9'] # из функции парсера

'Электроника'

Первое что пришло на ум для наглядности использовать структуру ввида:

In [39]:
{
    '000117a2a3': ['Электроника', '', '', '', '', '', ''],
    '0002983af3': ['Электроника', '', '', '', '', '', '']
}

{'000117a2a3': ['Электроника', '', '', '', '', '', ''],
 '0002983af3': ['Электроника', '', '', '', '', '', '']}

Данная структура, на мой взгляд, не самая оптимальная в для хранения и обработки данных, но моя цель обозначить, 
особенности обработки логов с использование словарей. Разумеется можно элементы массива кодировать более маленькими по размеру типами данных, 
например int или bool и в зависимости от позиции мапить с категорией - что вполне корректно применять в СУБД и не только.
Или же вообще использовать иную структуру, или даже несколько структур в разных переменных, в рамках применения задач инженера.
Но таковых решений может быть так же много как и самих задач.

Где каждый индекс массива имеет смысл категории:

In [40]:
categories = ['Электроника', 'Бытовая техника', 'Продукты', 'Досуг',
              'Строительство и ремонт', 'Товары для животных', 'не определена']


cat_pos = {c: i for i, c in enumerate(categories)}
cat_pos

{'Электроника': 0,
 'Бытовая техника': 1,
 'Продукты': 2,
 'Досуг': 3,
 'Строительство и ремонт': 4,
 'Товары для животных': 5,
 'не определена': 6}

In [41]:
# import numpy as np

# 1. Позиция каждой строки
df['pos'] = df['category'].map(cat_pos)

# 2. Оставить валидные
valid = df.dropna(subset=['pos']).copy()
valid['pos'] = valid['pos'].astype(int)

# 3. Оставить по одной строке на (user_id, pos)
pairs = valid[['user_id', 'pos']].drop_duplicates()

def _row_from_positions(positions, categories):
    row = [''] * len(categories)
    for p in positions:
        row[int(p)] = categories[int(p)]
    return row

# 4. Собрать словарь через groupby + apply
result = (
    pairs.groupby('user_id')['pos']
         .apply(lambda s: _row_from_positions(s, categories))
         .to_dict()
)

In [42]:
result

{'000117a2a3': ['Электроника', '', '', '', '', '', ''],
 '0002983af3': ['Электроника', '', '', '', '', '', ''],
 '0002b641bc': ['', 'Бытовая техника', '', '', '', '', ''],
 '000302625b': ['Электроника', '', '', '', '', '', ''],
 '0003962bbf': ['', '', '', 'Досуг', '', '', ''],
 '0003c135ea': ['', 'Бытовая техника', '', '', '', '', ''],
 '0003dea8e2': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00043e4c99': ['', '', '', 'Досуг', '', '', ''],
 '0004cbc893': ['', '', 'Продукты', '', '', '', ''],
 '0004ed9c1c': ['Электроника', '', '', '', '', '', ''],
 '0005a075bc': ['', '', 'Продукты', '', '', '', ''],
 '0005a1df4b': ['Электроника', '', '', '', '', '', ''],
 '0007b17b9c': ['', 'Бытовая техника', '', '', '', '', ''],
 '0007b4f64a': ['', 'Бытовая техника', '', '', '', '', ''],
 '0009a1123d': ['', 'Бытовая техника', '', '', '', '', ''],
 '0009df2bdb': ['', '', '', '', '', 'Товары для животных', ''],
 '000a12712b': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '000a8b81fe': ['', '', '', '', '', 'Товары для животных', ''],
 '000ac082d1': ['', '', 'Продукты', '', '', '', ''],
 '000aef2f75': ['', 'Бытовая техника', '', '', '', '', ''],
 '000b89d9b3': ['Электроника', '', '', '', '', '', ''],
 '000bf1e32a': ['', 'Бытовая техника', '', '', '', '', ''],
 '000e7a3d4d': ['', '', '', '', '', '', 'не определена'],
 '0010429e99': ['', '', 'Продукты', '', '', '', ''],
 '0011a3a56a': ['Электроника', '', '', '', '', '', ''],
 '0011a81b2d': ['Электроника', '', '', '', '', '', ''],
 '0011d635cd': ['Электроника', '', '', '', '', '', ''],
 '0011e16a61': ['', 'Бытовая техника', '', '', '', '', ''],
 '0012449d4b': ['', 'Бытовая техника', '', '', '', '', ''],
 '0015d9f8e6': ['Электроника', '', '', '', '', '', ''],
 '00186a1854': ['', 'Бытовая техника', '', '', '', '', ''],
 '00186fc278': ['', '', '', 'Досуг', '', '', ''],
 '0018fd2c49': ['', 'Бытовая техника', '', '', '', '', ''],
 '0019436b5c': ['', '', 'Продукты', '', '', '', ''],
 '0019c55dd8': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0019d4ffd8': ['Электроника', '', '', '', '', '', ''],
 '001b726565': ['', '', '', '', '', 'Товары для животных', ''],
 '001c7debc7': ['', '', 'Продукты', '', '', '', ''],
 '001c8fcb7a': ['', 'Бытовая техника', '', '', '', '', ''],
 '001f0756c6': ['', '', '', 'Досуг', '', '', ''],
 '001f58f21c': ['Электроника', '', '', '', '', '', ''],
 '001fceff38': ['', '', 'Продукты', '', '', '', ''],
 '00203a1d47': ['', '', 'Продукты', '', '', '', ''],
 '00212b1187': ['', 'Бытовая техника', '', '', '', '', ''],
 '00227d280c': ['Электроника', '', '', '', '', '', ''],
 '002440f7ae': ['', '', 'Продукты', '', '', '', ''],
 '00244d6439': ['', '', '', 'Досуг', '', '', ''],
 '002455d865': ['', '', '', 'Досуг', '', '', ''],
 '00245be1a1': ['Электроника', '', '', '', '', '', ''],
 '002559f2f5': ['', '', 'Продукты', '', '', '', ''],
 '0026df772c': ['', '', 'Продукты', '', '', '', ''],
 '00274655b2': ['Электроника', '', '', '', '', '', ''],
 '0027595057': ['', 'Бытовая техника', '', '', '', '', ''],
 '00276432e2': ['', '', '', '', '', 'Товары для животных', ''],
 '0027a20a57': ['', 'Бытовая техника', '', '', '', '', ''],
 '0028c9ac9f': ['', 'Бытовая техника', '', '', '', '', ''],
 '0029b06271': ['', '', 'Продукты', '', '', '', ''],
 '002aafac33': ['', '', 'Продукты', '', '', '', ''],
 '002acab764': ['', 'Бытовая техника', '', '', '', '', ''],
 '002af464cd': ['Электроника', '', '', '', '', '', ''],
 '002c2a855c': ['', 'Бытовая техника', '', '', '', '', ''],
 '002c469892': ['Электроника', '', '', '', '', '', ''],
 '002cc17f14': ['Электроника', '', '', '', '', '', ''],
 '002cc1d102': ['', '', 'Продукты', '', '', '', ''],
 '002daaebea': ['', '', 'Продукты', '', '', '', ''],
 '002df2a164': ['Электроника', '', '', '', '', '', ''],
 '002e39d330': ['', 'Бытовая техника', '', '', '', '', ''],
 '002f838ae9': ['Электроника', '', '', '', '', '', ''],
 '003165c05a': ['', '', 'Продукты', '', '', '', ''],
 '0031faf618': ['', '', 'Продукты', '', '', '', ''],
 '0032755ef3': ['Электроника', '', '', '', '', '', ''],
 '003304b7a4': ['Электроника', '', '', '', '', '', ''],
 '0034b6bdfb': ['Электроника', '', '', '', '', '', ''],
 '003589dc54': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '003595da77': ['', '', 'Продукты', '', '', '', ''],
 '003596d55c': ['', 'Бытовая техника', '', '', '', '', ''],
 '0035f903ef': ['', 'Бытовая техника', '', '', '', '', ''],
 '003654b16b': ['Электроника', '', '', '', '', '', ''],
 '003666807c': ['', 'Бытовая техника', '', '', '', '', ''],
 '003752a117': ['', 'Бытовая техника', '', '', '', '', ''],
 '00378a990b': ['Электроника', '', '', '', '', '', ''],
 '00383529da': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0039642c72': ['', '', 'Продукты', '', '', '', ''],
 '003964fb7c': ['', 'Бытовая техника', '', '', '', '', ''],
 '003a1b9469': ['', 'Бытовая техника', '', '', '', '', ''],
 '003a2f9c4e': ['', 'Бытовая техника', '', '', '', '', ''],
 '003adbe619': ['Электроника', '', '', '', '', '', ''],
 '003add66f0': ['', 'Бытовая техника', '', '', '', '', ''],
 '003dd13263': ['Электроника', '', '', '', '', '', ''],
 '003e2685d2': ['', '', 'Продукты', '', '', '', ''],
 '003e6a2a67': ['', '', '', 'Досуг', '', '', ''],
 '003f44a81d': ['', '', '', '', '', 'Товары для животных', ''],
 '003fa92348': ['', '', 'Продукты', '', '', '', ''],
 '003fb88683': ['', 'Бытовая техника', '', '', '', '', ''],
 '0040014392': ['', '', '', 'Досуг', '', '', ''],
 '0040888571': ['Электроника', '', '', '', '', '', ''],
 '0042243730': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '004320eab7': ['', 'Бытовая техника', '', '', '', '', ''],
 '00432147e4': ['Электроника', '', '', '', '', '', ''],
 '00440351bb': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00445b7847': ['', '', '', 'Досуг', '', '', ''],
 '00447c1892': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '004496ada1': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '004552bcfd': ['', 'Бытовая техника', '', '', '', '', ''],
 '00462f96a4': ['', '', '', 'Досуг', '', '', ''],
 '004633ff1a': ['Электроника', '', '', '', '', '', ''],
 '00487f3e69': ['', 'Бытовая техника', '', '', '', '', ''],
 '0048926cee': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0048e0bec7': ['', '', '', '', '', 'Товары для животных', ''],
 '004a2931f1': ['Электроника', '', '', '', '', '', ''],
 '004a2b90c3': ['Электроника', '', '', '', '', '', ''],
 '004a96b17a': ['', 'Бытовая техника', '', '', '', '', ''],
 '004ab95624': ['', '', '', 'Досуг', '', '', ''],
 '004b85421d': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '004b9a7d21': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '004bb0c786': ['Электроника', '', '', '', '', '', ''],
 '004c16141f': ['', '', 'Продукты', '', '', '', ''],
 '004c4247a2': ['', '', '', '', '', 'Товары для животных', ''],
 '004cc820a9': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '004e266876': ['', 'Бытовая техника', '', '', '', '', ''],
 '004e36da02': ['', '', 'Продукты', '', '', '', ''],
 '004e4cdfe6': ['', 'Бытовая техника', '', '', '', '', ''],
 '004eb1a203': ['', '', '', 'Досуг', '', '', ''],
 '004eb6925f': ['Электроника', '', '', '', '', '', ''],
 '004f0bb101': ['', '', '', 'Досуг', '', '', ''],
 '004ff1dcbd': ['', 'Бытовая техника', '', '', '', '', ''],
 '005046de03': ['', '', '', '', '', 'Товары для животных', ''],
 '0052bbbf59': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0052bdbcf9': ['', 'Бытовая техника', '', '', '', '', ''],
 '00536bf759': ['', '', 'Продукты', '', '', '', ''],
 '005412b7fe': ['', 'Бытовая техника', '', '', '', '', ''],
 '0054963a5d': ['', 'Бытовая техника', '', '', '', '', ''],
 '0055268bd2': ['', '', '', '', '', '', 'не определена'],
 '0056450cdf': ['Электроника', '', '', '', '', '', ''],
 '00565ccc59': ['Электроника', '', '', '', '', '', ''],
 '005684171e': ['Электроника', '', '', '', '', '', ''],
 '00577f12f1': ['', 'Бытовая техника', '', '', '', '', ''],
 '0057869227': ['', 'Бытовая техника', '', '', '', '', ''],
 '0058a14bc9': ['', '', 'Продукты', '', '', '', ''],
 '0059dcca87': ['Электроника', '', '', '', '', '', ''],
 '0059e2f18d': ['Электроника', '', '', '', '', '', ''],
 '005a00c135': ['', 'Бытовая техника', '', '', '', '', ''],
 '005a0cb500': ['Электроника', '', '', '', '', '', ''],
 '005a16853b': ['Электроника', '', '', '', '', '', ''],
 '005a841ddb': ['', 'Бытовая техника', '', '', '', '', ''],
 '005ae7a3f6': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '005b15c694': ['Электроника', '', '', '', '', '', ''],
 '005b4fd436': ['', '', 'Продукты', '', '', '', ''],
 '005c253871': ['', 'Бытовая техника', '', '', '', '', ''],
 '005cf1b5dd': ['Электроника', '', '', '', '', '', ''],
 '005d2ae1a3': ['', 'Бытовая техника', '', '', '', '', ''],
 '005da9d88f': ['', 'Бытовая техника', '', '', '', '', ''],
 '005dc16536': ['', '', '', 'Досуг', '', '', ''],
 '0060104fc1': ['Электроника', '', '', '', '', '', ''],
 '00607b4af6': ['Электроника', '', '', '', '', '', ''],
 '00612fb24c': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0061aaf3f9': ['Электроника', '', 'Продукты', '', '', '', ''],
 '0061f0ce50': ['', '', '', 'Досуг', '', '', ''],
 '006456c55c': ['Электроника', '', '', '', '', '', ''],
 '0064cf97b9': ['', '', 'Продукты', '', '', '', ''],
 '00658cb961': ['', '', '', '', '', 'Товары для животных', ''],
 '006600c579': ['Электроника', '', '', '', '', '', ''],
 '006617387a': ['Электроника', '', '', '', '', '', ''],
 '006689fbb0': ['', '', '', '', '', 'Товары для животных', ''],
 '0067667407': ['', 'Бытовая техника', '', '', '', '', ''],
 '0067845d4f': ['', '', '', '', '', 'Товары для животных', ''],
 '00687f0873': ['', 'Бытовая техника', '', '', '', '', ''],
 '0069fefa42': ['Электроника', '', '', '', '', '', ''],
 '006a2c4087': ['Электроника', '', '', '', '', '', ''],
 '006b1680a5': ['', '', '', 'Досуг', '', '', ''],
 '006b3238a5': ['Электроника', '', '', '', '', '', ''],
 '006b58f640': ['', '', '', '', '', 'Товары для животных', ''],
 '006b69682a': ['', 'Бытовая техника', '', '', '', '', ''],
 '006b8cef2f': ['Электроника', '', '', '', '', '', ''],
 '006c268405': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '006ce9ec29': ['', 'Бытовая техника', '', '', '', '', ''],
 '006d8cee5a': ['', '', '', 'Досуг', '', '', ''],
 '006e1a5a96': ['Электроника', '', '', '', '', '', ''],
 '006e4a5e9d': ['', 'Бытовая техника', '', '', '', '', ''],
 '006ecf3442': ['', '', '', 'Досуг', '', '', ''],
 '006ee454e2': ['', '', '', '', '', 'Товары для животных', ''],
 '006fc37b3e': ['', 'Бытовая техника', '', '', '', '', ''],
 '006ff5e95a': ['', '', '', 'Досуг', '', '', ''],
 '0070bcef50': ['', 'Бытовая техника', '', '', '', '', ''],
 '0071728397': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0071a25adb': ['', '', '', 'Досуг', '', '', ''],
 '0071fce131': ['', 'Бытовая техника', '', '', '', '', ''],
 '007394f015': ['', '', 'Продукты', '', '', '', ''],
 '0075115912': ['', 'Бытовая техника', '', '', '', '', ''],
 '0075c4b0eb': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00769b8761': ['', 'Бытовая техника', '', '', '', '', ''],
 '0076b63f0c': ['', '', '', '', '', 'Товары для животных', ''],
 '0076c58b8c': ['Электроника', '', '', '', '', '', ''],
 '00772995de': ['', '', '', '', '', 'Товары для животных', ''],
 '0077417aa0': ['', 'Бытовая техника', '', '', '', '', ''],
 '007767a5be': ['Электроника', '', '', '', '', '', ''],
 '0077ca9a6e': ['Электроника', '', '', '', '', '', ''],
 '0077ee1927': ['', '', 'Продукты', '', '', '', ''],
 '007828e7cf': ['Электроника', '', '', '', '', '', ''],
 '0078aaf92a': ['', '', '', 'Досуг', '', '', ''],
 '0079060493': ['', '', '', 'Досуг', '', '', ''],
 '007996fa56': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0079c27625': ['', 'Бытовая техника', '', '', '', '', ''],
 '0079cd0516': ['', '', 'Продукты', '', '', '', ''],
 '0079e05c3b': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '007b2b2e3e': ['', '', 'Продукты', '', '', '', ''],
 '007be39026': ['', '', 'Продукты', '', '', '', ''],
 '007d99160a': ['Электроника', '', '', '', '', '', ''],
 '007dfcf33d': ['', '', 'Продукты', '', '', '', ''],
 '007f3785d3': ['', '', 'Продукты', '', '', '', ''],
 '007f99efa6': ['Электроника', '', '', '', '', '', ''],
 '007fd92907': ['', 'Бытовая техника', '', '', '', '', ''],
 '0080271f17': ['', '', '', 'Досуг', '', '', ''],
 '0080cdd93b': ['', 'Бытовая техника', '', '', '', '', ''],
 '00822a9833': ['Электроника', '', '', '', '', '', ''],
 '008244a237': ['', '', '', 'Досуг', '', '', ''],
 '0082524258': ['', '', '', 'Досуг', '', '', ''],
 '0084c2cb61': ['', 'Бытовая техника', '', '', '', '', ''],
 '0085308fd6': ['', '', '', 'Досуг', '', '', ''],
 '00854ffda5': ['', '', '', '', '', 'Товары для животных', ''],
 '00855edc52': ['', 'Бытовая техника', '', '', '', '', ''],
 '0085b37d18': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00861493a9': ['Электроника', '', '', '', '', '', ''],
 '00866b956e': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0086bc27ae': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '0088061315': ['', '', '', '', '', 'Товары для животных', ''],
 '0088591d01': ['Электроника', '', '', '', '', '', ''],
 '0089343887': ['', '', '', 'Досуг', '', '', ''],
 '0089865701': ['', '', 'Продукты', '', '', '', ''],
 '0089925cba': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '008a45b9bb': ['', '', 'Продукты', '', '', '', ''],
 '008a587b98': ['', '', 'Продукты', '', '', '', ''],
 '008a95a7c4': ['Электроника', '', '', '', '', '', ''],
 '008b8f68ae': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '008c30268d': ['', '', '', 'Досуг', '', '', ''],
 '008cf01990': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '008e409fee': ['Электроника', '', '', '', '', '', ''],
 '008fd8257d': ['', 'Бытовая техника', '', '', '', '', ''],
 '009138ecce': ['Электроника', '', '', '', '', '', ''],
 '0092043689': ['', 'Бытовая техника', '', '', '', '', ''],
 '00920f3110': ['', 'Бытовая техника', '', '', '', '', ''],
 '0092b55d0f': ['', 'Бытовая техника', '', '', '', '', ''],
 '0093561fe1': ['', '', '', 'Досуг', '', '', ''],
 '0093ce99ba': ['', 'Бытовая техника', '', '', '', '', ''],
 '0093d20e2d': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '009437a523': ['', '', 'Продукты', '', '', '', ''],
 '0094cf2778': ['Электроника', '', '', '', '', '', ''],
 '0094dcf60c': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '009532301c': ['', '', '', '', '', 'Товары для животных', ''],
 '00954ac206': ['', 'Бытовая техника', '', '', '', '', ''],
 '0095e2600d': ['Электроника', '', '', '', '', '', ''],
 '009604e2d9': ['', '', '', '', '', 'Товары для животных', ''],
 '00961dff28': ['', 'Бытовая техника', '', '', '', '', ''],
 '0096286acd': ['', '', '', 'Досуг', '', '', ''],
 '00963af70e': ['', '', '', '', '', '', 'не определена'],
 '009813503a': ['Электроника', '', '', '', '', '', ''],
 '0098a9ed2c': ['', '', '', '', '', 'Товары для животных', ''],
 '009906aa8e': ['', 'Бытовая техника', '', '', '', '', ''],
 '00997ad899': ['Электроника', '', '', '', '', '', ''],
 '009a17e161': ['', 'Бытовая техника', '', '', '', '', ''],
 '009aa7a570': ['Электроника', '', '', '', '', '', ''],
 '009afacbee': ['Электроника', '', '', '', '', '', ''],
 '009b68e0ab': ['', 'Бытовая техника', '', '', '', '', ''],
 '009b70006b': ['', '', 'Продукты', '', '', '', ''],
 '009bb5da14': ['Электроника', '', '', '', '', '', ''],
 '009c0014ca': ['Электроника', '', '', '', '', '', ''],
 '009ce03a92': ['Электроника', '', '', '', '', '', ''],
 '009d1a31f2': ['', '', '', 'Досуг', '', '', ''],
 '009e57c2ba': ['', 'Бытовая техника', '', '', '', '', ''],
 '009ee3a915': ['', '', '', 'Досуг', '', '', ''],
 '009eeb6810': ['', '', 'Продукты', '', '', '', ''],
 '009f02813e': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a02c9a80': ['Электроника', '', '', '', '', '', ''],
 '00a047b7e6': ['Электроника', '', '', '', '', '', ''],
 '00a08e9ad5': ['Электроника', '', '', '', '', '', ''],
 '00a0db8b01': ['', '', '', 'Досуг', '', '', ''],
 '00a1640962': ['Электроника', '', '', '', '', '', ''],
 '00a2b08255': ['Электроника', '', '', '', '', '', ''],
 '00a2eeb6c3': ['Электроника', '', '', '', '', '', ''],
 '00a2f8393c': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a32ab2a5': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a356822f': ['Электроника', '', '', '', '', '', ''],
 '00a417ca7a': ['', '', 'Продукты', '', '', '', ''],
 '00a4a5bf1c': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a4ca40dd': ['Электроника', '', '', '', '', '', ''],
 '00a4cbdd51': ['Электроника', '', '', '', '', '', ''],
 '00a6531f03': ['', '', 'Продукты', '', '', '', ''],
 '00a6c8cfe3': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a6e0e0b3': ['', '', '', '', '', 'Товары для животных', ''],
 '00a6ea1d13': ['Электроника', '', '', '', '', '', ''],
 '00a72da960': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a7caa494': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a7dd3899': ['', '', '', 'Досуг', '', '', ''],
 '00a82d3ac8': ['Электроника', '', '', '', '', '', ''],
 '00a8730306': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a94fd037': ['', '', '', '', '', '', 'не определена'],
 '00a9d22891': ['', 'Бытовая техника', '', '', '', '', ''],
 '00a9d42565': ['', 'Бытовая техника', '', '', '', '', ''],
 '00aa13a58a': ['', '', '', 'Досуг', '', '', ''],
 '00ab055cbd': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00ac0711e7': ['', '', 'Продукты', '', '', '', ''],
 '00ac62e18a': ['', 'Бытовая техника', '', '', '', '', ''],
 '00ad705b70': ['', '', 'Продукты', '', '', '', ''],
 '00ad80d668': ['Электроника', '', '', '', '', '', ''],
 '00adbc65a2': ['', 'Бытовая техника', '', '', '', '', ''],
 '00adbfb1f3': ['Электроника', '', '', '', '', '', ''],
 '00aebced06': ['', 'Бытовая техника', '', '', '', '', ''],
 '00af163a57': ['Электроника', '', '', '', '', '', ''],
 '00b0fd6c6e': ['', '', '', 'Досуг', '', '', ''],
 '00b11c89d9': ['Электроника', '', '', '', '', '', ''],
 '00b15a767b': ['', '', '', '', '', 'Товары для животных', ''],
 '00b1d89362': ['', 'Бытовая техника', '', '', '', '', ''],
 '00b2245c80': ['Электроника', '', '', '', '', '', ''],
 '00b2703626': ['', '', '', 'Досуг', '', '', ''],
 '00b4aa66c2': ['Электроника', '', '', '', '', '', ''],
 '00b5baf214': ['Электроника', '', '', '', '', '', ''],
 '00b6760703': ['', '', 'Продукты', '', '', '', ''],
 '00b6c12242': ['', '', 'Продукты', '', '', '', ''],
 '00b7042173': ['', '', '', '', '', 'Товары для животных', ''],
 '00b732d8c5': ['Электроника', '', '', '', '', '', ''],
 '00b76a470f': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00b7a3b1f0': ['', '', '', 'Досуг', '', '', ''],
 '00b84c2261': ['', 'Бытовая техника', '', '', '', '', ''],
 '00bb91e442': ['', 'Бытовая техника', '', '', '', '', ''],
 '00bc29c41d': ['Электроника', '', '', '', '', '', ''],
 '00bccc06d3': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00bd823af9': ['', 'Бытовая техника', '', '', '', '', ''],
 '00bde28a54': ['Электроника', '', '', '', '', '', ''],
 '00bde55594': ['', '', '', 'Досуг', '', '', ''],
 '00bdff6c17': ['Электроника', '', '', '', '', '', ''],
 '00bfca5ec4': ['', 'Бытовая техника', '', '', '', '', ''],
 '00c027e8c8': ['', 'Бытовая техника', '', '', '', '', ''],
 '00c097a5bd': ['Электроника', '', '', '', '', '', ''],
 '00c0eb50e2': ['', 'Бытовая техника', '', '', '', '', ''],
 '00c0f50a34': ['Электроника', '', '', '', '', '', ''],
 '00c28227ef': ['Электроника', '', '', '', '', '', ''],
 '00c2b136d9': ['', '', '', 'Досуг', '', '', ''],
 '00c2ec10b0': ['Электроника', '', '', '', '', '', ''],
 '00c3b5f6db': ['', '', '', '', 'Строительство и ремонт', '', ''],
 '00c3dfd592': ['', 'Бытовая техника', '', '', '', '', ''],
 '00c40043ad': ['Электроника', '', '', '', '', '', ''],
 '00c417cc63': ['', '', '', '', '', 'Товары для животных', ''],
 '00c44bd37f': ['Электроника', '', '', '', '', '', ''],
 '00c5094aae': ['Электроника', '', '', '', '', '', ''],
 '00c754ad6c': ['', '', '', '', '', 'Товары для животных', ''],
 '00c83efdc4': ['', '', '', 'Досуг', '', '', ''],

Да следует отметить изменился порядок. Но поскольку это хэш таблица с доступом по ключу O(1), то порядок не важен.

In [43]:
result.get('0061aaf3f9')

['Электроника', '', 'Продукты', '', '', '', '']

# ДЗ 2

В условии задачи сказано что чанк не должен помещаться полностью в ОЗУ, и нужно считывать построчно. 
Применю похожее условие и для предварительного анализа.

## Предварительный просмотр исходных данных

In [44]:
with open('visit_log.csv', 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        if i >= 5 : break
        line = line.strip()
        # обработка строки
        print(line)

user_id,source
6450655ae8,other
b4ea53e670,other
0,other
96064ae9e0,other

Примерно понятна структура данных. Далее я постарлся избежать подключения сторонних библиотек для выполнения задачи. В реальной боевой системе допускаю появления спец символов, которых в ДЗ нет.

## Решение

В этот раз не оформлял код в виде функции

In [45]:
with \
    open('visit_log.csv', 'r', encoding='utf-8') as f_visit, \
    open('funnel.csv', 'w', encoding='utf-8', newline='') as f_funnel:
    f_visit.readline() # сдвигаю курсор на заголовок
    f_funnel.write('user_id,source,category\n')
    for i, line_visit in enumerate(f_visit):
        user_id, source = line_visit.strip().split(',')
        if user_id in p1:
            f_funnel.write(f'{user_id},{source},{p1[user_id]}\n')

In [46]:
with open('funnel.csv', 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        if i >= 3 : break
        line = line.strip()
        # обработка строки
        print(line)

user_id,source,category
1840e0b9d4,other,Продукты
4e4f90fcfb,context,Электроника

## Решение с учетом дублей из аналитического блока ДЗ 1

Если использовать решение, которое учитывает несколько категорий, то значительно решение не измениться.

В качестве контрольного пользователя беру идентификатор: `0061aaf3f9`

In [47]:
with \
    open('visit_log.csv', 'r', encoding='utf-8') as f_visit, \
    open('funnel_2.csv', 'w', encoding='utf-8', newline='') as f_funnel:
    f_visit.readline() # сдвигаю курсор на заголовок
    f_funnel.write('user_id,source,categories\n')
    for i, line_visit in enumerate(f_visit):
        user_id, source = line_visit.strip().split(',')
        if user_id in p1:
            f_funnel.write(f'{user_id},{source},{";".join([i for i in result[user_id] if i != ""])}\n')

In [48]:
with open('funnel_2.csv', 'r', encoding='utf-8') as f_funnel_2:
    head = f_funnel_2.readline().strip()
    print(head)
    for i, line_funnel in enumerate(f_funnel_2):
        user_id, source, categories = line_funnel.strip().split(',')
        if '0061aaf3f9' == user_id:
            print(f'{user_id}, {source}, {categories}')

user_id,source,categories
0061aaf3f9, other, Электроника;Продукты
0061aaf3f9, context, Электроника;Продукты